export const VARIABLE_TYPES = {
  COLOR: "COLOR",
  FLOAT: "FLOAT",
  STRING: "STRING",
  FONT_WEIGHT: "FONT_WEIGHT",
  FONT_SIZE: "FONT_SIZE",
  LINE_HEIGHT: "LINE_HEIGHT",
  FONT_FAMILY: "FONT_FAMILY",
};

export const COLLECTION_NAMES = {
  SKIN: "Brand",
  COLOR_SCHEME: "Mode",
  PALETTE: "Palette",
};

export const MODE_NAMES = {
  DEFAULT: "Mode 1",
  LIGHT: "Light",
  DARK: "Dark",
};

export const VARIABLE_SCOPES = {
  ALL_SCOPES: "ALL_SCOPES",
  CORNER_RADIUS: "CORNER_RADIUS",
  FONT_WEIGHT: "FONT_WEIGHT",
  FONT_SIZE: "FONT_SIZE",
  LINE_HEIGHT: "LINE_HEIGHT",
  FONT_FAMILY: "FONT_FAMILY",
  TEXT_CONTENT: "TEXT_CONTENT",
  WIDTH_HEIGHT: "WIDTH_HEIGHT",
  GAP: "GAP",
};

export const BRANDS = {
  AI_NATIVE_SOC: "cybersecurity",
};
