changelog:
  issues:
    exclude:
      labels: ["suggestions", "stale", "library: resources"]
  contributors:
    exclude:
      names: ["yceballost", "aweell", "AnaMontes11"]
  sections:
    - title: "⚠️ Breaking changes"
      labels: ["breaking change", "library: mobile"]
      group: "📱 Mística Mobile"
    - title: "⚠️ Breaking changes"
      labels: ["breaking change", "library: desktop"]
      group: "🖥 Mística Desktop"
    - title: "✨ New!"
      labels: ["new!"]
    - title: "Changes (Figma)"
      labels: ["library: mobile"]
      group: "📱 Mística Mobile"
    - title: "Bugs fixed (Figma)"
      labels: ["library: mobile", "bug 🐞"]
      group: "📱 Mística Mobile"
    - title: "Changes (Figma)"
      labels: ["library: desktop"]
      group: "🖥 Mística Desktop"
    - title: "Bugs fixed (Figma)"
      labels: ["library: desktop", "bug 🐞"]
      group: "🖥 Mística Desktop"
    - title: "💅 Brand changes"
      labels:
        [
          "brand: movistar",
          "brand: vivo",
          "brand: o2",
          "brand: classic o2",
          "brand: telefónica",
          "brand: blau",
        ]
