changelog:
  sections:
    - title: "Breaking changes"
      labels: ["breaking change"]
    - title: "Changes in Mística Mobile (Figma)"
      labels: ["library: mobile"]
    - title: "Changes in Mística Desktop (Figma)"
      labels: ["library: desktop"]
    - title: "Enhancements"
      labels: ["enhancements"]
    - title: "Bugs"
      labels: ["bug 🐞"]
