changelog:
  issues:
    exclude:
      labels:
        [
          "suggestions",
          "stale",
          "platform: android",
          "platform: ios",
          "platform: web",
          "library: resources",
        ]
  contributors:
    exclude:
      names: ["yceballost", "aweell", "AnaMontes11"]
  sections:
    - title: "⚠️ Breaking changes"
      labels: ["breaking change"]
    - title: "✨ New!"
      labels: ["breaking change"]
    - title: "📱 Mística Mobile changes (Figma)"
      labels: ["library: mobile"]
    - title: "🖥 Mística Desktop changes (Figma)"
      labels: ["library: desktop"]
    - title: "💅 Brand changes"
      labels:
        [
          "brand: movistar",
          "brand: vivo",
          "brand: o2",
          "brand: classic o2",
          "brand: telefónica",
          "brand: blau",
        ]
    - title: "📱 Mística Mobile enhancements (Figma)"
      labels: ["library: mobile"]
    - title: "🖥 Mística Desktop enhancements (Figma)"
      labels: ["library: desktop"]
    - title: "🐞 Bugs fixed"
      labels: ["bug 🐞"]
