changelog:
  issues:
    exclude:
      labels: ["suggestions", "stale", "library: resources"]
  contributors:
    exclude:
      names: ["yceballost", "aweell", "AnaMontes11"]
  sections:
    - title: "✨ New!"
      labels: ["new!"]
      sort: "title"
      group: "New"
    - title: "⚠️ Breaking changes"
      labels: ["breaking change"]
      group: "Breaking changes"
      sort: "title"
    - title: "Changes"
      labels: ["library: mobile", "library: desktop"]
      group: "Changes"
      sort: "title"
    - title: "Bugs fixed"
      labels: ["bug 🐞"]
      group: "Bugs"
      sort: "title"
    - title: "Movistar"
      labels: ["brand: movistar"]
      sort: "title"
      group: "Brand changes"
    - title: "Movistar"
      labels: ["brand: movistar"]
      sort: "title"
      group: "Brand changes"
    - title: "Vivo"
      labels: ["brand: vivo"]
      sort: "title"
      group: "Brand changes"
    - title: "O<sub>2<sub>"
      labels: ["brand: o2"]
      sort: "title"
      group: "Brand changes"
    - title: "Classic O2"
      labels: ["brand: classic o2"]
      sort: "title"
      group: "Brand changes"
    - title: "Telefónica"
      labels: ["brand: telefónica"]
      sort: "title"
      group: "Brand changes"
    - title: "Blau"
      labels: ["brand: blau"]
      sort: "title"
      group: "Brand changes"
    - title: "Solar 360"
      labels: ["brand: solar360"]
      sort: "title"
      group: "Brand changes"
    # - title: "💅 Brand changes"
    #   labels:
    #     [
    #       "brand: movistar",
    #       "brand: vivo",
    #       "brand: o2",
    #       "brand: classic o2",
    #       "brand: telefónica",
    #       "brand: blau",
    #     ]
    - title: "⚙️ Icon changes"
      labels: ["fundamentals: icons"]
      sort: "title"
    - title: "✒️ Typography changes"
      labels: ["fundamentals: typography"]
      sort: "title"
    - title: "📒 Documentation changes"
      labels: ["category: documentation"]
      sort: "title"
