changelog:
  issues:
    exclude:
      labels: ["suggestions", "stale", "library: resources"]
  contributors:
    exclude:
      names: ["yceballost", "aweell", "AnaMontes11"]
  sections:
    - title: "⚠️ Breaking changes"
      labels: ["breaking change"]
    - title: "✨ New!"
      labels: ["new!"]
    - title: "📱 Mística Mobile changes (Figma)"
      labels: ["library: mobile"]
    - title: "🖥 Mística Desktop changes (Figma)"
      labels: ["library: desktop"]
    - title: "📱 Mística Mobile bugs (Figma)"
      labels: ["library: mobile", "bug 🐞"]
    - title: "🖥 Mística Desktop bugs (Figma)"
      labels: ["library: desktop", "bug 🐞"]
    - title: "💅 Brand changes"
      labels:
        [
          "brand: movistar",
          "brand: vivo",
          "brand: o2",
          "brand: classic o2",
          "brand: telefónica",
          "brand: blau",
        ]
