changelog:
  issues:
    exclude:
      labels: ["suggestions", "stale", "library: resources"]
  contributors:
    exclude:
      names: ["aaa", "aweell", "AnaMontes11"]
  sections:
    - title: "✨ New!"
      labels: ["new!"]
    - title: "📱 ⚠️ Breaking changes in Mística Mobile (Figma)"
      labels: ["breaking change", "library: mobile"]
      group: "BB Mística Mobile"
    - title: "📱 Changes in Mística Mobile (Figma)"
      labels: ["library: mobile"]
      group: "Changes Mística Mobile"
    - title: "📱 Bugs fixed in Mística Mobile (Figma)"
      labels: ["library: mobile", "bug 🐞"]
      group: "Bugs Mística Mobile"
    - title: "🖥 ⚠️ Breaking changes in Mística Desktop (Figma)"
      labels: ["breaking change", "library: desktop"]
      group: "BB Mística Desktop"
    - title: "🖥 Changes in Mística Desktop (Figma)"
      labels: ["library: desktop"]
      group: "Changes Mística Desktop"
    - title: "🖥 Bugs fixed in Mística Desktop (Figma)"
      labels: ["library: desktop", "bug 🐞"]
      group: "Bugs Mística Desktop"
    - title: "Movistar"
      labels: ["brand: movistar"]
      group: "Brand changes"
    - title: "Movistar"
      labels: ["brand: movistar"]
      group: "Brand changes"
    - title: "Vivo"
      labels: ["brand: vivo"]
      group: "Brand changes"
    - title: "O<sub>2<sub>"
      labels: ["brand: o2"]
      group: "Brand changes"
    - title: "Classic O2"
      labels: ["brand: classic o2"]
      group: "Brand changes"
    - title: "Telefónica"
      labels: ["brand: telefónica"]
      group: "Brand changes"
    - title: "Blau"
      labels: ["brand: blau"]
      group: "Brand changes"
    - title: "Solar 360"
      labels: ["brand: solar360"]
      group: "Brand changes"
    # - title: "💅 Brand changes"
    #   labels:
    #     [
    #       "brand: movistar",
    #       "brand: vivo",
    #       "brand: o2",
    #       "brand: classic o2",
    #       "brand: telefónica",
    #       "brand: blau",
    #     ]
    - title: "📒 Documentation changes"
      labels: ["category: documentation"]
