changelog:
  sections:
    - title: "Breaking changes"
      labels: ["breaking change"]
    - title: "Changes in Mística Mobile (Figma)"
      labels: ["library: mobile"]
    - title: "Changes in Mística Desktop (Figma)"
      labels: ["library: desktop"]
    - title: "Brand changes"
      labels:
        [
          "brand: movistar",
          "brand: vivo",
          "brand: o2",
          "brand: classic o2",
          "brand: telefónica",
          "brand: blau",
        ]
    - title: "Enhancements"
      labels: ["enhancements"]
    - title: "Bugs"
      labels: ["bug 🐞"]
