import type { AnyNode, TextNode } from "../figma/types.ts";
import { slugifyName } from "../figma/url.ts";
import { getSpecSections } from "../parser/walk.ts";
import { emitH2 } from "../parser/h2.ts";
import {
  emitH3,
  getH3TextNodes,
  toH3Block,
  type H3Block,
} from "../parser/h3.ts";
import { getFigureFramesInSection } from "../parser/figure.ts";
import { getTableFramesInSection, type TableFrame } from "../parser/table.ts";
import {
  emitFigure,
  replaceInlineFigures,
  type FigureRef,
} from "../parser/inline.ts";
import {
  appendIfChanged,
  emitChangelog,
  type ChangelogEntry,
} from "./changelog.ts";

export interface RenderInput {
  componentSlug: string;
  fileKey: string;
  pageId: string;
  page: AnyNode;
  generatedAt: Date;
  /** Map of `${sectionSlug}::${figureSlug}` → exported PNG metadata. */
  figuresByKey: Map<string, FigureRef>;
  /** Map of `${sectionSlug}::${tableSlug}` → pre-rendered markdown. */
  tablesByKey: Map<string, string>;
  /** Branch label + Figma lastModified for this run. */
  changelog: {
    previous: ChangelogEntry[];
    current: ChangelogEntry;
  };
  /** Mutated to collect human-readable warnings during render. */
  warnings?: string[];
}

type SectionItem =
  | { kind: "h3"; y: number; block: H3Block }
  | { kind: "table"; y: number; frame: TableFrame };

export function renderMarkdown(input: RenderInput): string {
  const sections = getSpecSections(input.page);
  const consumed = new Set<string>();
  const warnings = input.warnings ?? [];
  const parts: string[] = [];

  parts.push(buildHeader(input));
  parts.push(`# ${humanize(input.componentSlug)}`);

  const updatedChangelog = appendIfChanged(
    input.changelog.previous,
    input.changelog.current,
  );
  const changelogMd = emitChangelog(updatedChangelog);
  if (changelogMd) parts.push(changelogMd);

  for (const section of sections) {
    parts.push(emitH2(section));

    const sectionFigures = getFigureFramesInSection(section, warnings);
    const sectionTables = getTableFramesInSection(section, warnings);
    const sectionSlug = slugifyName(section.name);
    const keyOf = (figSlug: string) => `${sectionSlug}::${figSlug}`;

    const emitFigureBySlug = (figSlug: string): boolean => {
      const key = keyOf(figSlug);
      if (consumed.has(key)) return false;
      const ref = input.figuresByKey.get(key);
      if (!ref) return false;
      consumed.add(key);
      parts.push(emitFigure(ref));
      return true;
    };

    // Place a figure whose slug matches the H2 section name right under the heading.
    for (const fig of sectionFigures) {
      if (fig.slug === sectionSlug) emitFigureBySlug(fig.slug);
    }

    const items: SectionItem[] = [];
    for (const node of getH3TextNodes(section)) {
      const block = toH3Block(node);
      block.body = replaceInlineFigures(
        block.body,
        input.figuresByKey,
        sectionSlug,
        consumed,
        warnings,
      );
      items.push({ kind: "h3", y: yOf(node), block });
    }
    for (const t of sectionTables) {
      items.push({ kind: "table", y: t.y, frame: t });
    }
    items.sort((a, b) => a.y - b.y);

    const figureSlugsInSection = new Set(sectionFigures.map((f) => f.slug));

    for (const item of items) {
      if (item.kind === "h3") {
        parts.push(emitH3(item.block));
        // Try the full-path slug first (e.g. `Default/Header` → `default-header`),
        // then fall back to the title-only slug (`header`) for backward compat.
        const pathSlug = slugifyName(item.block.pathSegments.join("/"));
        const titleSlug = slugifyName(item.block.title);
        if (pathSlug && figureSlugsInSection.has(pathSlug)) {
          emitFigureBySlug(pathSlug);
        } else if (titleSlug && figureSlugsInSection.has(titleSlug)) {
          emitFigureBySlug(titleSlug);
        }
      } else {
        const rendered = input.tablesByKey.get(keyOf(item.frame.slug));
        if (rendered) {
          parts.push(rendered);
        } else {
          warnings.push(
            `No rendered output for table::${item.frame.slug} — skipping.`,
          );
        }
      }
    }

    // Append remaining unconsumed figures from this section, in canvas y-order.
    for (const fig of sectionFigures) emitFigureBySlug(fig.slug);
  }

  return normalizeBlankLines(parts.join("\n\n").trimEnd()) + "\n";
}

function yOf(node: TextNode | AnyNode): number {
  return node.absoluteBoundingBox?.y ?? 0;
}

function buildHeader(input: RenderInput): string {
  return [
    "<!--",
    "  Generated by scripts/figma-spec — do not edit by hand.",
    `  component: ${input.componentSlug}`,
    `  fileKey:   ${input.fileKey}`,
    `  pageId:    ${input.pageId}`,
    `  generated: ${input.generatedAt.toISOString()}`,
    "-->",
  ].join("\n");
}

function humanize(slug: string): string {
  return slug
    .split(/[-_]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function normalizeBlankLines(s: string): string {
  // Collapse 3+ consecutive newlines to a single blank line.
  return s.replace(/\n{3,}/g, "\n\n");
}
