name: Bug report 🐛
description: Create a report to help us improve the Mística libraries
title: ""
labels: "bug 🐞"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report to improve Mística!
