blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://teams.microsoft.com/l/team/19%3ad2e3607a32ec411b8bf492f43cd0fe0c%40thread.tacv2/conversations?groupId=e265fe99-929f-45d1-8154-699649674a40&tenantId=9744600e-3e04-492e-baa1-25ec245c6f10
    about: Please ask questions in our Microsoft Teams.