blank_issues_enabled: false
contact_links:
  - name: 🐛 Report Bug Icon
    url: https://github.com/Telefonica/mistica-icons/issues/new?assignees=yceballost&labels=Bug+%F0%9F%90%9E&template=bug_report.md&title=
    about: Report bugs in icons
  - name: ✨ Icon Request
    url: https://github.com/Telefonica/mistica-icons/issues/new?assignees=&labels=%E2%9C%A8+Icon+request&template=icon_request.md&title=
    about: Contribute to Mística Design System integrating icons
  - name: Questions
    url: https://teams.microsoft.com/l/team/19%3ad2e3607a32ec411b8bf492f43cd0fe0c%40thread.tacv2/conversations?groupId=e265fe99-929f-45d1-8154-699649674a40&tenantId=9744600e-3e04-492e-baa1-25ec245c6f10
    about: Please ask questions in our Microsoft Teams.
    