blank_issues_enabled: false
contact_links:
  - name: ✨ Icon Request
    url: https://github.com/Telefonica/mistica-icons/issues/new?assignees=&labels=%E2%9C%A8+Icon+request&template=icon_request.md&title=
    about: Contribute to Mística Design System with integrating icons