blank_issues_enabled: false
contact_links:
  - name: 🐛 Report Bug Icon
    url: https://github.com/Telefonica/mistica-icons/issues/new?assignees=yceballost&labels=Bug+%F0%9F%90%9E&template=bug_report.md&title=
    about: Report bugs in icons