import "@telefonica/mistica/css/reset.css";
import {
  Stack,
  Box,
  ResponsiveLayout,
  MediaCard,
  ButtonLink,
  Text7,
  Text4,
  Header,
  Image,
  HeaderLayout,
  GridLayout,
  BoxedRow,
  BoxedRowList,
  skinVars,
  useScreenSize,
} from "@telefonica/mistica";
import React from "react";
import "@telefonica/mistica/css/mistica.css";
import wrapperCover from "./img/wrapper_cover.png";

const App = () => {
  const { isDesktopOrBigger } = useScreenSize();

  return (
    <Box>
      <HeaderLayout
        isInverse={false}
        header={<Header />}
        extra={
          <Stack space={16}>
            <Text7>Mística Index</Text7>
            <Text4>A list of little internal projects for Mística Design</Text4>
          </Stack>
        }
      />

      <ResponsiveLayout>
        <GridLayout
          template="8+4"
          left={
            <Box
              paddingY={isDesktopOrBigger ? 40 : 24}
              paddingRight={isDesktopOrBigger ? 64 : undefined}
              paddingBottom={isDesktopOrBigger ? 104 : 24}
            >
              <Stack space={40}>
                {/* <Title2>Mística Index</Title2> */}
                <div
                  style={{
                    display: "grid",
                    gridTemplateColumns: "repeat(auto-fill, minmax(50%, 1fr))",
                    gap: isDesktopOrBigger ? 24 : 16,
                  }}
                >
                  <MediaCard
                    media={<Image aspectRatio="16:9" src={wrapperCover} />}
                    title="Mística Wrapper '22"
                    description="Data summary on what has happened in the year 2022 in Mística."
                    buttonLink={
                      <ButtonLink
                        href="https://tinyurl.com/2fyfjdnw"
                        newTab={true}
                      >
                        Visit
                      </ButtonLink>
                    }
                  />
                  <MediaCard
                    media={
                      <Image
                        aspectRatio="16:9"
                        src="https://images.unsplash.com/photo-1526758405662-5998b5bee9ec?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80"
                      />
                    }
                    title="Tokens Table"
                    description="Table with all colors equivalence between brands"
                    buttonLink={
                      <ButtonLink href="tokens/index.html">Visit</ButtonLink>
                    }
                  />
                  <MediaCard
                    media={
                      <Image
                        aspectRatio="16:9"
                        src="https://images.unsplash.com/photo-1516383274235-5f42d6c6426d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1748&q=80"
                      />
                    }
                    title="Repo Dashboard"
                    description="Autogenerated dasboard using GitHub repository information"
                    buttonLink={
                      <ButtonLink href="dashboard/index.html">Visit</ButtonLink>
                    }
                  />
                </div>
              </Stack>
            </Box>
          }
          right={
            <Box paddingY={isDesktopOrBigger ? 40 : 800}>
              <BoxedRowList>
                <BoxedRow title="Design Documentation" onPress={() => {}} />
                <BoxedRow title="GitHub Repository" onPress={() => {}} />
                <BoxedRow title="Title" onPress={() => {}} />
              </BoxedRowList>
            </Box>
          }
        />
      </ResponsiveLayout>
    </Box>
  );
};

export default App;
