name: "pre-release"

on:
  push:
    branches:
      - "production"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{github.event.commits[0].message}}"
          prerelease: true
          title: "${{github.event.commits[0].message}}"
          files: |
            LICENSE.txt
            *.jar
