name: Changelog index generator

# Trigger the workflow on milestone events
on:
  workflow_dispatch:
  push:
    branches:
      - production
    paths:
      - ".github/resources/changelog-index-generator.py"
      - "changelog-versions/**"

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.NOVUM_PRIVATE_REPOS }}

      - run: sudo python3 .github/resources/changelog-index-generator.py changelog-versions

      - name: Commit & Push
        run: |
          git add .
          git config user.name "github-actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "update changelog"
          git push origin production
