name: Changelog generator

# Trigger the workflow on milestone events
on:
  milestone:
    types: [closed]
  workflow_dispatch:
    inputs:
      milestoneId:
        description: "Milestone ID"
        required: true
        default: "1"

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Release Notes
        uses: docker://decathlon/release-notes-generator-action:3.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          FILENAME: CHANGELOG
          USE_MILESTONE_TITLE: "true"

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "update changelog"

      - name: Push to protected branch
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          branch: production
          unprotect_reviews: true
