name: Changelog index generator

# Trigger the workflow on milestone events
on:
  workflow_dispatch:
  push:
    branches:
      - pre-production
      - production
    paths:
      - ".github/resources/changelog-index-generator.py"
      - "changelog-versions/**"

jobs:
  changelog-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get branch name
        uses: rlespinasse/github-slug-action@v3.x

      - run: sudo python3 .github/resources/changelog-index-generator.py changelog-versions

      - name: Commit & Push in ${{ env.GITHUB_REF_SLUG_URL }}
        run: |
          git add .
          git config user.name "github-actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "update changelog"
          git push origin ${{ env.GITHUB_REF_SLUG_URL }}
