name: ChatGPT Reviewer

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  chatgpt:
    runs-on: ubuntu-latest
    steps:
      - uses: platisd/openai-pr-description@master
        with:
          github_token: ${{ secrets.NOVUM_PRIVATE_REPOS }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
