name: Code Review

permissions:
  contents: read
  pull-requests: write

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: OpenAI ChatGPT Code Review
        uses: adshao/chatgpt-code-review-action@main
        with:
          PROGRAMMING_LANGUAGE: "JavaScript"
          REVIEW_COMMENT_PREFIX: "chatgpt:"
          FULL_REVIEW_COMMENT: "chatgpt"
          OPENAI_TOKEN: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.NOVUM_PRIVATE_REPOS }}
