name: Build Dashboard

on:
  push:
    paths:
      - ".github/workflows/dashboard.yml"
  issues:
    types: [opened, closed, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      uses: allanwsilva/check-pending-tasks@v1.0.0
      with:
        sendgrid-from-email: valid@email.com
        email-subject: "Check out these Github tasks assigned to you that are still pending"
      env:
        GITHUB_TOKEN: ${{ secrets.NOVUM_PRIVATE_REPOS }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
