name: New component request notification

on:
  issues:
    types: [labeled]

jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.PERSONAL_TOKEN }}"
        project-url: "https://github.com/Telefonica/mistica-design/projects/2"
        column-name: "Bug reported"
        label-name: "Bug 🐞"
