name: Cloning folder libraries to mistica-sketch-libraries — PRODUCTION

on:
  push:
    branches: 
    - production
  schedule:
    - cron:  "03 03 * * *"

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Components (production)
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_branch: production
        src_path: /Component Libraries/.
        dst_branch: production
        dst_path: /Component Libraries/.
        dst_owner: yceballost
        dst_repo_name: mistica-sketch-libraries
        clean: true