name: "Skin Validator"

on:
  pull_request:
    paths:
      - "tokens/**"
    branches:
      - pre-production
      - production

jobs:
  Movistar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate action.yml against a remote schema
        uses: cardinalby/schema-validator-action@v1
        with:
          file: "tokens/movistar.json"
          schema: "tokens/schema/skin-schema.json"

  O2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate action.yml against a remote schema
        uses: cardinalby/schema-validator-action@v1
        with:
          file: "tokens/o2.json"
          schema: "tokens/schema/skin-schema.json"

  O2-new:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate action.yml against a remote schema
        uses: cardinalby/schema-validator-action@v1
        with:
          file: "tokens/o2-new.json"
          schema: "tokens/schema/skin-schema.json"

  Vivo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate action.yml against a remote schema
        uses: cardinalby/schema-validator-action@v1
        with:
          file: "tokens/vivo.json"
          schema: "tokens/schema/skin-schema.json"

  Vivo-new:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate action.yml against a remote schema
        uses: cardinalby/schema-validator-action@v1
        with:
          file: "tokens/vivo-new.json"
          schema: "tokens/schema/skin-schema.json"

  Telefonica:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate action.yml against a remote schema
        uses: cardinalby/schema-validator-action@v1
        with:
          file: "tokens/telefonica.json"
          schema: "tokens/schema/skin-schema.json"

  Blau:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate action.yml against a remote schema
        uses: cardinalby/schema-validator-action@v1
        with:
          file: "tokens/blau.json"
          schema: "tokens/schema/skin-schema.json"
