name: "Schema validator"

on:
  pull_request:

jobs:
  skins_validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate action.yml against a remote schema
        uses: cardinalby/schema-validator-action@v1
        with:
          file: "tokens/*.json"
          schema: "tokens/schema/skin-schema.json"
