name: "Schema validator"

on:
  pull_request:

jobs:
  movistar-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate action.yml against a remote schema
        uses: cardinalby/schema-validator-action@v1
        with:
          file: "tokens/movistar.json"
          schema: "tokens/schema/skin-schema.json"

  o2-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate action.yml against a remote schema
        uses: cardinalby/schema-validator-action@v1
        with:
          file: "tokens/o2.json"
          schema: "tokens/schema/skin-schema.json"

  vico-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate action.yml against a remote schema
        uses: cardinalby/schema-validator-action@v1
        with:
          file: "tokens/vivo.json"
          schema: "tokens/schema/skin-schema.json"

  telefonica-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate action.yml against a remote schema
        uses: cardinalby/schema-validator-action@v1
        with:
          file: "tokens/telefonica.json"
          schema: "tokens/schema/skin-schema.json"

  blau-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate action.yml against a remote schema
        uses: cardinalby/schema-validator-action@v1
        with:
          file: "tokens/blau.json"
          schema: "tokens/schema/skin-schema.json"

  classic-o2-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate action.yml against a remote schema
        uses: cardinalby/schema-validator-action@v1
        with:
          file: "tokens/classic-o2.json"
          schema: "tokens/schema/skin-schema.json"

  solar360-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate action.yml against a remote schema
        uses: cardinalby/schema-validator-action@v1
        with:
          file: "tokens/solar-360.json"
          schema: "tokens/schema/skin-schema.json"
