name: Cloning libraries to mistica-sketch-libraries

on:
  schedule:
    - cron:  "00 03 * * 1"

jobs:
  generator:
    runs-on: ubuntu-latest
    steps:

    # comando solo para Self-Hosted machines
    # - run: sudo chown -R $USER:$USER /home/pi/actions-runner/_work/test-action

    - uses: actions/checkout@v2

    - name: Get branch name
      uses: rlespinasse/github-slug-action@v2.x

    - run: sudo npm install --global kactus-cli

    - name: convert folder to sketch file
      run: |
        kactus import libs/Movistar_Brand_Library
        kactus import libs/O2_Brand_Library
        kactus import libs/ClassicO2_Brand_Library
        kactus import libs/Vivo_Brand_Library
        kactus import libs/Telefonica_Brand_Library
        kactus import libs/iOS_Novum_Library
        kactus import libs/Android_Novum_Library

    - name: stage changed files
      run: git add -f .

    - name: config
      run: |
        git config --global user.name "🤖GeneratorBot"
        git config --global user.email "users.noreply.github.com"

    - name: commit changed files
      run: git commit -m "sketch generated and folders removed"

    - name: push code to ${{ env.GITHUB_REF_SLUG_URL }}
      run: git push origin HEAD:${{ env.GITHUB_REF_SLUG_URL }}
    
    - name: Copy Brands to ${{ env.GITHUB_REF_SLUG_URL }}
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_branch: ${{ env.GITHUB_REF_SLUG_URL }}
        src_path: libs/.
        file_filter: '*.sketch'
        dst_branch: ${{ env.GITHUB_REF_SLUG_URL }}
        dst_path: libraries/.
        dst_owner: yceballost
        dst_repo_name: mistica-sketch-libraries
        commit_message: Libs uploaded to ${{ env.GITHUB_REF_SLUG_URL }}
        clean: true
    
    - name: removed sketch force
      run: |
        git rm *.sketch
        git commit -m "sketch removed"
        git push origin HEAD:${{ env.GITHUB_REF_SLUG_URL }}
