name: Cloning libraries to mistica-sketch-libraries

on:
  push:
    branches:
      - production
      - develop

jobs:
  send-files:
    needs: generator
    runs-on: [self-hosted, Linux]
    steps:
    # comando solo para Self-Hosted machines
    - run: sudo chown -R $USER:$USER /home/pi/actions-github/mistica-design-libraries/_work/

    - name: Get branch name
      uses: rlespinasse/github-slug-action@v2.x

    - name: Copy Brands to ${{ env.GITHUB_REF_SLUG_URL }}
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_branch: ${{ env.GITHUB_REF_SLUG_URL }}
        src_path: libs/.
        file_filter: '*.sketch'
        dst_branch: ${{ env.GITHUB_REF_SLUG_URL }}
        dst_path: libraries/.
        dst_owner: yceballost
        dst_repo_name: mistica-sketch-libraries
        commit_message: Libs uploaded to ${{ env.GITHUB_REF_SLUG_URL }}
        clean: true