name: Sync tokens to Figma

on:
  workflow_dispatch:
  push:
    branches:
      - production
    paths:
      - "tokens/movistar.json"
      - "tokens/movistar-new.json"
      - "tokens/vivo-new.json"
      - "tokens/o2-new.json"
      - "tokens/telefonica.json"
      - "tokens/blau.json"
      - "tokens/tu.json"
      - "tokens/esimflag.json"

permissions:
  contents: read

env:
  FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}

jobs:
  sync-figma-brand:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install dependencies
        working-directory: tokens/figma
        run: npm install

      - name: Run sync for the brand(s)
        working-directory: tokens/figma
        run: node index.mjs
