name: Sync tokens to Figma

on:
  push:
    branches:
      - production
    paths:
      - "tokens/movistar.json"
      - "tokens/vivo-new.json"
      - "tokens/o2-new.json"
      - "tokens/telefonica.json"
      - "tokens/blau.json"
      - "tokens/tu.json"

  workflow_dispatch:
    inputs:
      movistar:
        type: boolean
        default: true
      vivo-new:
        type: boolean
        default: true
      o2-new:
        type: boolean
        default: true
      telefonica:
        type: boolean
        default: true
      blau:
        type: boolean
        default: true
      tu:
        type: boolean
        default: true

jobs:
  sync-figma-brand:
    runs-on: ubuntu-latest

    env:
      FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
      MOVISTAR_FILE_KEY: ${{ secrets.MOVISTAR_FILE_KEY }}
      VIVO_NEW_FILE_KEY: ${{ secrets.VIVO_NEW_FILE_KEY }}
      O2_NEW_FILE_KEY: ${{ secrets.O2_NEW_FILE_KEY }}
      TELEFONICA_FILE_KEY: ${{ secrets.TELEFONICA_FILE_KEY }}
      BLAU_FILE_KEY: ${{ secrets.BLAU_FILE_KEY }}
      TU_FILE_KEY: ${{ secrets.TU_FILE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Filter changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            movistar:
              - 'tokens/movistar.json'
            vivo-new:
              - 'tokens/vivo-new.json'
            o2-new:
              - 'tokens/o2-new.json'
            telefonica:
              - 'tokens/telefonica.json'
            blau:
              - 'tokens/blau.json'
            tu:
              - 'tokens/tu.json'

      - name: Determine Execution Mode
        id: determine-mode
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            selected_brands=""
            if [ "${{ github.event.inputs.movistar }}" == "true" ]; then
              selected_brands+=" movistar"
            fi
            if [ "${{ github.event.inputs.vivo-new }}" == "true" ]; then
              selected_brands+=" vivo-new"
            fi
            if [ "${{ github.event.inputs.o2-new }}" == "true" ]; then
              selected_brands+=" o2-new"
            fi
            if [ "${{ github.event.inputs.telefonica }}" == "true" ]; then
              selected_brands+=" telefonica"
            fi
            if [ "${{ github.event.inputs.blau }}" == "true" ]; then
              selected_brands+=" blau"
            fi
            if [ "${{ github.event.inputs.tu }}" == "true" ]; then
              selected_brands+=" tu"
            fi
            echo "Selected brands: $selected_brands"
            echo "BRAND_NAME=$selected_brands" >> $GITHUB_ENV
          else
            selected_brands=""
            if [ "${{ steps.filter.outputs.movistar }}" == "true" ]; then
              selected_brands+=" movistar"
            fi
            if [ "${{ steps.filter.outputs.vivo-new }}" == "true" ]; then
              selected_brands+=" vivo-new"
            fi
            if [ "${{ steps.filter.outputs.o2-new }}" == "true" ]; then
              selected_brands+=" o2-new"
            fi
            if [ "${{ steps.filter.outputs.telefonica }}" == "true" ]; then
              selected_brands+=" telefonica"
            fi
            if [ "${{ steps.filter.outputs.blau }}" == "true" ]; then
              selected_brands+=" blau"
            fi
            if [ "${{ steps.filter.outputs.tu }}" == "true" ]; then
              selected_brands+=" tu"
            fi
            echo "Detected changes in brands: $selected_brands"
            echo "BRAND_NAME=$selected_brands" >> $GITHUB_ENV
          fi

      - name: Run sync for the brand(s)
        working-directory: tokens/figma
        run: |
          for brand in $BRAND_NAME; do
            echo "Syncing brand: $brand"
            node test.mjs "$brand"
          done
