name: Sync tokens to Figma

on:
  push:
    branches:
      - production
    paths:
      - "tokens/movistar.json"
      - "tokens/vivo-new.json"
      - "tokens/o2-new.json"
      - "tokens/telefonica.json"
      - "tokens/blau.json"
      - "tokens/tu.json"

  workflow_dispatch:
    inputs:
      movistar:
        type: boolean
        default: true
      vivo-new:
        type: boolean
        default: true
      o2-new:
        type: boolean
        default: true
      telefonica:
        type: boolean
        default: true
      blau:
        type: boolean
        default: true
      tu:
        type: boolean
        default: true

jobs:
  sync-figma-brand:
    runs-on: ubuntu-latest

    env:
      FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
      MOVISTAR_FILE_KEY: ${{ secrets.MOVISTAR_FILE_KEY }}
      VIVO_FILE_KEY: ${{ secrets.VIVO_FILE_KEY }}
      TELEFONICA_FILE_KEY: ${{ secrets.TELEFONICA_FILE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine Execution Mode
        id: determine-mode
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            # Get the name of the modified file (e.g., "movistar.json")
            FILE_NAME=$(git diff --name-only HEAD^ HEAD | grep 'tokens/' | xargs basename)
            # Remove the ".json" extension to get the brand name
            BRAND_NAME="${FILE_NAME%.json}"
            echo "Triggered by push. Brand: $BRAND_NAME"
            echo "BRAND_NAME=$BRAND_NAME" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            selected_brands=""
            if [ "${{ github.event.inputs.movistar }}" == "true" ]; then
              selected_brands+=" movistar"
            fi
            if [ "${{ github.event.inputs.vivo-new }}" == "true" ]; then
              selected_brands+=" vivo-new"
            fi
            if [ "${{ github.event.inputs.o2-new }}" == "true" ]; then
              selected_brands+=" o2-new"
            fi
            if [ "${{ github.event.inputs.telefonica }}" == "true" ]; then
              selected_brands+=" telefonica"
            fi
            if [ "${{ github.event.inputs.blau }}" == "true" ]; then
              selected_brands+=" blau"
            fi
            if [ "${{ github.event.inputs.tu }}" == "true" ]; then
              selected_brands+=" tu"
            fi
            echo "Triggered by workflow dispatch. Selected brands: $selected_brands"
            echo "BRAND_NAME=$selected_brands" >> $GITHUB_ENV
          fi

      - name: Run sync for the brand(s)
        working-directory: tokens/figma
        run: |
          for brand in $BRAND_NAME; do
            echo "Syncing brand: $brand"
            node test.mjs "$brand"
          done
