name: Sync tokens to Figma

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - "tokens/*.json"
  workflow_dispatch:
    inputs:
      Movistar:
        type: boolean
        default: true
      Vivo-new:
        type: boolean
        default: true
      O2-new:
        type: boolean
        default: true
      Telefónica:
        type: boolean
        default: true
      Blau:
        type: boolean
        default: true
      Tu:
        type: boolean
        default: true
    # inputs:
    #   brand:
    #     description: "Select the brand to update variables in Figma"
    #     required: true
    #     "all"
    #     type: choice
    #     options:
    #       - all
    #       - movistar
    #       - o2-new
    #       - vivo-new
    #       - telefonica
    #       - blau
    #       - tu

jobs:
  sync-figma-brands:
    runs-on: ubuntu-latest

    env:
      # Remember to sync these with the index.mjs file
      FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
      MOVISTAR_FILE_KEY: ${{ secrets.MOVISTAR_FILE_KEY }}
      O2_NEW_FILE_KEY: ${{ secrets.O2_NEW_FILE_KEY }}
      VIVO_NEW_FILE_KEY: ${{ secrets.VIVO_NEW_FILE_KEY }}
      TELEFONICA_FILE_KEY: ${{ secrets.TELEFONICA_FILE_KEY }}
      BLAU_FILE_KEY: ${{ secrets.BLAU_FILE_KEY }}
      TU_FILE_KEY: ${{ secrets.TU_FILE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "16"

      # - name: Install npm dependencies
      #   run: npm install

      - id: get-brand
        uses: joao-zanutto/get-selected@v1.1.1

      - name: Sync ${{ steps.get-brand.outputs.selected }}
        working-directory: tokens/figma
        run: |
          node index.mjs ${{ steps.get-brand.outputs.selected }}

      # - name: Sync Mística Skins
      #   working-directory: tokens/figma
      #   run: |
      #     node index.mjs ${{ github.event.inputs.brand }}
