name: Sync tokens to Figma

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - "tokens/*.json"
  workflow_dispatch:
    inputs:
      movistar:
        type: boolean
        default: true
      vivo-new:
        type: boolean
        default: true
      o2-new:
        type: boolean
        default: true
      telefonica:
        type: boolean
        default: true
      blau:
        type: boolean
        default: true
      tu:
        type: boolean
        default: true

jobs:
  sync-figma-brands:
    runs-on: ubuntu-latest

    env:
      # Remember to sync these with the index.mjs file
      FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
      MOVISTAR_FILE_KEY: ${{ secrets.MOVISTAR_FILE_KEY }}
      O2_NEW_FILE_KEY: ${{ secrets.O2_NEW_FILE_KEY }}
      VIVO_NEW_FILE_KEY: ${{ secrets.VIVO_NEW_FILE_KEY }}
      TELEFONICA_FILE_KEY: ${{ secrets.TELEFONICA_FILE_KEY }}
      BLAU_FILE_KEY: ${{ secrets.BLAU_FILE_KEY }}
      TU_FILE_KEY: ${{ secrets.TU_FILE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "16"

      # - name: Install npm dependencies
      #   run: npm install

      - id: get-brand
        uses: joao-zanutto/get-selected@v1.1.1

      - name: Run sync for each selected brand
        working-directory: tokens/figma
        run: |
          selected_brands="${{ steps.get-brand.outputs.selected }}"
          for brand in ${selected_brands}; do
            node index.mjs $brand
          done

      # - name: Sync Mística Skins
      #   working-directory: tokens/figma
      #   run: |
      #     node index.mjs ${{ github.event.inputs.brand }}
